###
GET http://localhost:5000/users

###
GET http://localhost:5000/user/create
Content-Type: application/json

{
    "role":"User",
    "email":"maria.hessen@banana.cz",
    "password":198900
}

###
POST http://localhost:5000/details/user
Content-Type: application/json

{
		"name":"name",
		"body_type": 2,
		"hair_color": 0,
		"personality_type": 11,
		"hobbies": 0,
		"zodiac": 2,
		"gender": 2,
		"location": {"longitude":42, "latitude":32},
		"description":"I am very interesting, pick me!",
		"age": 35

}

###
POST http://localhost:5000/test/route
Content-Type: application/json

{
		"name":"Elias",
		"personality_type": 10,
		"zodiac": 9,
		"age": 18

}